# Use root/example as user/password credentials
version: "3"

volumes:
  vmpostgres: 
    external: false

# networks:
#   mongonet:
#     external: true
services:
  postgres14:
    image: public.ecr.aws/ubuntu/postgres:12-20.04_beta
    ports:
      - 5400:5432
    environment:
      POSTGRES_PASSWORD: SQLserver2012
    volumes:
      - vmpostgres:/var/lib/postgresql/data